// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:ba6dc832-47e3-42ab-8cda-86a42e39d254',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactivenativelogin-hosting-mobilehub-1933883807',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1md7y18ej36du.cloudfront.net',
    'aws_mobile_analytics_app_id': 'bab92b6822e24c3e8be9bca056e9dedd',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '15fc4aab-b4ef-45c0-85e2-5e883b572e7b',
    'aws_project_name': 'reactiveNativeLogin',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'reactivenativelogin-mobilehub-1933883807',
}

export default awsmobile;
